# Generated by Django 2.0.3 on 2018-04-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_calendar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='calendar_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
