# Generated by Django 2.0.3 on 2018-04-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180404_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='estimated_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
