# Generated by Django 2.0.3 on 2018-04-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_work_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
