# Generated by Django 2.0.3 on 2018-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180408_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
