# Generated by Django 2.0.3 on 2018-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='due_date',
            field=models.DateField(),
        ),
    ]
