# Generated by Django 2.0.3 on 2018-04-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180421_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
    ]
